export const PAGEROUTE = 'PAGEROUTE';
export const ADDTOBANK = 'ADDTOBANK';
export const EDITBANK = 'EDITBANK';
export const OVERWRITEBANK = 'OVERWRITEBANK';
export const DELETEBANK = 'DELETEBANK';
export const CHANGEFORM = 'CHANGEFORM';
export const RESETALERTBOX = 'RESETALERTBOX';
export const RETRIEVESTATE = 'RETRIEVESTATE'; 